### ISSUE TITLE
[FEATURE] Adding RegexValidator

### ISSUE THREAD

**Issue by Moongazer** [CPS-IT/project-builder#151]
### Is your feature request related to a problem?

It would be very useful if we could force the naming of some custom variables using regular-expressions. A use-case is the convention policy of an agency, e.g. to use customer specific short hand symbols everywhere (for tickets, branches, folder-names, etc.).

As example, the agency policy says a customer symbol must consist of 3 letters:
Project name: CPS TYPO3
Customer name: Coding Powerful Systems
Customer symbol: cps

The customer symbol is used agency wide e.g. for
- folder names: `EXT:cps_customextension`
- tickets: `CPS: Issue title`
- branches: `cps/issue-123`

### Describe the solution you'd like

A RegexValidator could be used like this:
```
properties:
  # Project
  - identifier: project
    name: Project
    properties:
    # ...
      - identifier: customer_symbol
        name: Customer symbol
        type: staticValue
        validators:
          - type: notEmpty
          - type: regexp
            rule: '/^[a-z]{3}$/'
            errorMessage: 'The customer symbol must consist of 3 lower-case characters!'
```
The option `errorMessage` could be optional to show a proper Regex explanation instead of a default error-message like `"The input provided for PROPERTYNAME does not match the regular-expression of 'RULE'!"`
