### ISSUE TITLE
[BUG] .twig fileendings are not removed when copied

### ISSUE THREAD

**Issue by Tim-Obert** [CPS-IT/project-builder#392]
### PHP version

8.2.13

### Composer version

2.3.0

### Package version

2.6.0

### Operating system

Windows 11 / WSL Debian 11

### Current behavior

If a directory is specified in the processSourceFiles step, the files remain ".twig" files.
The variables are replaced correctly, but the file name remains the same. 
If the folder is removed from the fileConditions, the files are renamed correctly.

### Expected behavior

The templates are processed and the ".twig" then disappears afterwards.

### Steps to reproduce

config.yaml: 

 ```yaml
name: TYPO3 CMS project

steps:
  - type: collectBuildInstructions
  - type: processSourceFiles
    options:
      fileConditions:
        - path: 'local_packages/sitepackage/*'
          target: 'local_packages/{{ project.sitepackage_name }}/*'
        # Deployer
        - path: '.gitlab-ci/*'
          if: 'features["deployer"]'
  - type: generateBuildArtifact
  - type: mirrorProcessedFiles
  - type: showNextSteps
    options:
      templateFile: templates/next-steps.html.twig

properties:
  # Project
  - identifier: project
    name: Project
    properties:
      - identifier: name
        name: Project name
        type: staticValue
        validators:
          - type: notEmpty
      - identifier: sitepackage_name
        name: Sitepackage Name
        type: staticValue
        defaultValue: "sitepackage_{{ project.name|slugify|convert_case('snake') }}"
        validators:
          - type: notEmpty
 ```

in src/local_packages/sitepackage/.composer.json.twig:
```json
{
	"name": "{{ project.sitepackage_name}}",
	"type": "typo3-cms-extension",
	"homepage": "{{ project.url }}",
	"license": ["GPL-2.0-or-later"],
	"keywords": ["TYPO3 CMS"],
	"require": {
		"typo3/cms-core": "^12.4"
	}
}
```
